# Generated by Django 4.2.13 on 2026-05-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('platform', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=10)),
                ('certificate_url', models.URLField(blank=True)),
                ('certificate_image', models.ImageField(blank=True, null=True, upload_to='certifications/')),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Certifications',
                'ordering': ['-display_order', '-issued_date'],
            },
        ),
        migrations.AddField(
            model_name='experience',
            name='role',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='experience',
            name='skills_learned',
            field=models.TextField(blank=True, help_text='List of skills learned or outcomes'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_type',
            field=models.CharField(choices=[('job', 'Job'), ('internship', 'Internship'), ('training', 'Training')], default='job', max_length=20),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
