# Generated by Django 4.2.13 on 2026-05-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_blog_slug_alter_blogcategory_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='experience_type',
            field=models.CharField(choices=[('job', 'Job'), ('internship', 'Internship'), ('freelance', 'Freelance'), ('training', 'Training')], default='job', max_length=20),
        ),
    ]
